### ISSUE TITLE
UnicodeDecodeError in compress templatetag

### ISSUE THREAD

**Issue by kylefox** [dziegler/django-css#17]
We have one LESS file being included in our base.html template:

```
{% compress css %}
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/screen.less" type="text/css" media="screen, projection">
{% endcompress %}
```

It works fine on our local machines, but on the server we get a UnicodeDecodeError (see below).  Has anyone else seen this or know how to fix it?

We will investigate further, just thought I'd post an issue in case other people are seeing the same thing.

  TemplateSyntaxError: Caught an exception while rendering: Traceback (most recent call last):
    File "/usr/local/lib/python2.6/dist-packages/django_css-2.2.1-py2.6.egg/compressor/templatetags/compress.py", line 42, in render
      output = compressor.output()
    File "/usr/local/lib/python2.6/dist-packages/django_css-2.2.1-py2.6.egg/compressor/**init**.py", line 178, in output
      url = "%s/%s" % (settings.MEDIA_URL.rstrip('/'), self.new_filepath)
    File "/usr/local/lib/python2.6/dist-packages/django_css-2.2.1-py2.6.egg/compressor/**init**.py", line 148, in new_filepath
      filename = "".join([self.hash, self.extension])
    File "/usr/local/lib/python2.6/dist-packages/django_css-2.2.1-py2.6.egg/compressor/**init**.py", line 144, in hash
      return get_hexdigest(self.combined)[:12]
    File "/usr/local/lib/python2.6/dist-packages/django_css-2.2.1-py2.6.egg/compressor/**init**.py", line 135, in combined
      output = self.concat()
    File "/usr/local/lib/python2.6/dist-packages/django_css-2.2.1-py2.6.egg/compressor/**init**.py", line 118, in concat
      return "\n".join(self.hunks)
    File "/usr/local/lib/python2.6/dist-packages/django_css-2.2.1-py2.6.egg/compressor/**init**.py", line 112, in hunks
      input = self.filter(input, 'input', filename=v, elem=elem)
    File "/usr/local/lib/python2.6/dist-packages/django_css-2.2.1-py2.6.egg/compressor/**init**.py", line 126, in filter
      content = filter(**kwargs)
    File "/usr/local/lib/python2.6/dist-packages/django_css-2.2.1-py2.6.egg/compressor/filters/css_default.py", line 20, in input
      output = url_pattern.sub(self.url_converter, self.content)
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16: ordinal not in range(128)

**Comment by kylefox** [comment]
Whatever caused this was apparently fixed: using the latest revision resolved the issue.

**Comment by dziegler** [comment]
I love it when I fix bugs on accident.
