### ISSUE TITLE
Cleverss inserts an extra letter into path on windows

### ISSUE THREAD

**Issue by drozzy** [dziegler/django-css#31]
On windows, when I try to start my django project I get the following exception:

Caught Exception while rendering: Traceback (most recent call last): File "C:\Python27\Scripts\clevercss-script.py", line 8, in <module> load_entry_point('CleverCSS==0.1.4', 'console_scripts', 'clevercss')() File "build\bdist.win-amd64\egg\clevercss.py", line 1590, in main IOError: [Errno 2] No such file or directory: 'C:\Users\blahblah\Projects\client\core\media\a\ccss\block.ccss'

NOTE that the actual path is:
C:\Users\blahblah\Projects\client\core\media\ccss\block.ccss'

Note that this path does not have a letter "a" between "media" and "ccss".

**Comment by drozzy** [comment]
Also, it uses double slashes \ on windows - but for some reason git-hub's parser removed them.

**Comment by drozzy** [comment]
Closed by accident.
