### ISSUE TITLE
Tests fail.

### ISSUE THREAD

**Issue by monokrome** [dziegler/django-css#36]
The following output occurs when I try to run tests, because it is looking for a file that is not part of your package. It is looking for the testing package - but that package doesn't exist after I've installed your application. Hence, failure.

~: ./manage.py test --failfast
    Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <type 'exceptions.AttributeError'> ignored
    Creating test database for alias 'default'...................................................................................................................................................................................................................................................................................................................................................Exception RuntimeError: 'maximum recursion depth exceeded in **subclasscheck**' in <type 'exceptions.AttributeError'> ignored
    .Exception RuntimeError: 'maximum recursion depth exceeded in **subclasscheck**' in <type 'exceptions.AttributeError'> ignored
    .Exception RuntimeError: 'maximum recursion depth exceeded in **subclasscheck**' in <type 'exceptions.AttributeError'> ignored
    .......................................................E
    ======================================================================
    ERROR: test_css_hash (compressor.tests.CompressorTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/monokrome/Projects/reo/lib/python2.6/site-packages/compressor/tests.py", line 133, in test_css_hash
        self.assertEqual(self.css_hash, self.cssNode.hash)
      File "/Users/monokrome/Projects/reo/lib/python2.6/site-packages/compressor/**init**.py", line 138, in hash
        return get_hexdigest(self.combined)[:12]
      File "/Users/monokrome/Projects/reo/lib/python2.6/site-packages/compressor/**init**.py", line 129, in combined
        output = self.concat()
      File "/Users/monokrome/Projects/reo/lib/python2.6/site-packages/compressor/**init**.py", line 110, in concat
        return "\n".join(self.hunks)
      File "/Users/monokrome/Projects/reo/lib/python2.6/site-packages/compressor/**init**.py", line 94, in hunks
        for kind, v, elem in self.split_contents():
      File "/Users/monokrome/Projects/reo/lib/python2.6/site-packages/compressor/**init**.py", line 263, in split_contents
        self.compile(path,settings.COMPILER_FORMATS[ext])
      File "/Users/monokrome/Projects/reo/lib/python2.6/site-packages/compressor/**init**.py", line 207, in compile
        raise Exception(err)
    Exception: python: can't open file '/Users/monokrome/Projects/reo/lib/python2.6/site-packages/compressor/../testing/clevercss.py': [Errno 2] No such file or directory

```
----------------------------------------------------------------------
Ran 394 tests in 6.551s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by monokrome** [comment]
I have forked this repository and am sending a pull request that fixes all tests. They now pass on my build server.
